
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: ./app/api
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build: ./app/frontend
    ports:
      - "5001:5000"
    environment:
      - API_SERVICE_HOST=api
      - API_SERVICE_PORT=5000
    depends_on:
      - api

volumes:
  redis_data:
