apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubesight.fullname" . }}-config
  labels:
    {{- include "kubesight.labels" . | nindent 4 }}
    app.kubernetes.io/component: common
data:
  VERBOSE: "{{ .Values.common.VERBOSE }}"
  VERSION: "{{ .Values.common.VERSION }}"
  COMMIT_SHA: "{{ .Values.common.COMMIT_SHA }}"
  ENVIRONMENT: "{{ .Values.common.ENVIRONMENT }}"