---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubesight.fullname" . }}-redis
  labels:
    {{- include "kubesight.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
  selector:
    {{- include "kubesight.selectorLabels" . | nindent 6 }}
    {{- "app.kubernetes.io/component: redis" | nindent 6 }}