apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubesight.fullname" . }}-secret
  labels:
    {{- include "kubesight.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
{{- toYaml .Values.secret | nindent 2 }}